services:
  db:
    image: postgres:16-alpine
    container_name: oshadhi_db
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: sriharshareddy6464/doc-backend:v1.0.1
    container_name: oshadhi_backend
    restart: always
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: 5000
      FRONTEND_URL: ${FRONTEND_URL}
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
    ports:
      - "5000:5000"

  frontend:
    image: sriharshareddy6464/doc-frontend:v1.0.1
    container_name: oshadhi_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data: