{
 "title": "infrastucture overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Services Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "EC2 CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EC2 Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EC2 Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 -\r\n  (\r\n    node_filesystem_avail_bytes{device=\"/dev/root\", mountpoint=\"/etc/hostname\"}\r\n    /\r\n    node_filesystem_size_bytes{device=\"/dev/root\", mountpoint=\"/etc/hostname\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}