/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: '#0058bc',
        primaryDark: '#004494',
        primaryDeep: '#001a41',
        primaryLight: '#adc6ff',
        primaryFaded: '#f0f3ff',
        accent: '#ff9f43',
        background: '#f9f9ff',
        surface: '#ffffff',
        surfaceAlt: '#f8fafc',
        card: '#ffffff',
        navyDark: '#151c27',
        textMain: '#151c27',
        textSecondary: '#5c6571',
        textTertiary: '#727784',
        textInverse: '#ffffff',
        textLink: '#0058bc',
        border: '#c2c6d5',
        borderLight: '#e2e8f8',
        divider: '#c2c6d5',
        success: '#10B981',
        successLight: '#d1fae5',
        warning: '#af6100',
        warningLight: '#ffdcc2',
        danger: '#ba1a1a',
        dangerLight: '#ffdad6',
        info: '#0058bc',
        infoLight: '#d8e2ff',
        overlay: 'rgba(21, 28, 39, 0.4)',
        shadow: 'rgba(0, 88, 188, 0.05)',
        statusConfirmed: '#0058bc',
        statusCompleted: '#10B981',
        statusCancelled: '#ba1a1a',
        statusPending: '#af6100',
        statusApproved: '#10B981',
        statusRejected: '#ba1a1a',
        statusInProgress: '#8b4c00',
        statusScheduled: '#0058bc',
        statusPaid: '#10B981',
        statusRefunded: '#af6100',
      }
    },
  },
  plugins: [],
}
